/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employee.payroll;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class Deducoes extends javax.swing.JFrame 
{

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    /**
     * Creates new form Deducoes
     */
    public Deducoes() 
    {
        initComponents();
        
        conn = db.java_db();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_deducacao_search = new javax.swing.JTextField();
        txt_deducao_ID = new javax.swing.JTextField();
        txt_deducao_nome = new javax.swing.JTextField();
        txt_deducao_apelido = new javax.swing.JTextField();
        txt_deducao_dataNascimento = new javax.swing.JTextField();
        txt_deducao_departamento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_deducao_designacao = new javax.swing.JTextField();
        txt_deducao_status = new javax.swing.JTextField();
        txt_deducao_dateHired = new javax.swing.JTextField();
        txt_deducao_categoria = new javax.swing.JTextField();
        txt_deducao_salario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        radio_deducao_percentagem = new javax.swing.JRadioButton();
        radio_deducao_montante = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        txt_deducao_percentagem = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_deducao_montante = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lbl_total_deduzir = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbl_salario_deduzido = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_deducao_motivos = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        label_deducao_loggedAs = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Pesquisar (ID):");

        jLabel2.setText("Staff ID:");

        jLabel3.setText("Nome:");

        jLabel4.setText("Apelido:");

        jLabel5.setText("Data de Nascimento:");

        jLabel6.setText("Departamento:");

        txt_deducacao_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_deducacao_searchActionPerformed(evt);
            }
        });
        txt_deducacao_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_deducacao_searchKeyReleased(evt);
            }
        });

        jLabel8.setText("Desiganacao:");

        jLabel7.setText("Status:");

        jLabel9.setText("Data de contratacao:");

        jLabel10.setText("Categoria:");

        jLabel11.setText("Salario Base:");

        txt_deducao_salario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_deducao_salarioActionPerformed(evt);
            }
        });

        jLabel12.setText("Actualizar salario:");

        radio_deducao_percentagem.setText("Percentagem(%)");
        radio_deducao_percentagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_deducao_percentagemActionPerformed(evt);
            }
        });

        radio_deducao_montante.setText("Montante");
        radio_deducao_montante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_deducao_montanteActionPerformed(evt);
            }
        });

        jLabel13.setText("Percentagem:");

        jLabel14.setText("Montante:");

        txt_deducao_montante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_deducao_montanteActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Total a deduzir:");

        lbl_total_deduzir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_total_deduzir.setText("0.00");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Salario deduzido:");

        lbl_salario_deduzido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_salario_deduzido.setText("0.00");

        jLabel19.setText("Justificativo:");

        jButton1.setText("Salavar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Limpar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel20.setText("Logged In As:");

        label_deducao_loggedAs.setText("staff");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(label_deducao_loggedAs))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(txt_deducacao_search, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel20)
                                .addComponent(jLabel12)))
                        .addGap(30, 30, 30)
                        .addComponent(txt_deducao_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel19)
                                .addComponent(jLabel13))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jButton1)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton2)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton3))
                                        .addComponent(txt_deducao_motivos, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(txt_deducao_percentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_deducao_montante, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(64, 64, 64)
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_salario_deduzido))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(166, 166, 166)
                                    .addComponent(radio_deducao_percentagem))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txt_deducao_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_deducao_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_deducao_apelido, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_deducao_dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(radio_deducao_montante)))
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_deducao_designacao)
                                    .addComponent(txt_deducao_status)
                                    .addComponent(txt_deducao_salario)
                                    .addComponent(txt_deducao_dateHired)
                                    .addComponent(txt_deducao_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(34, 34, 34)
                                    .addComponent(lbl_total_deduzir))))))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_deducacao_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_deducao_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txt_deducao_designacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txt_deducao_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txt_deducao_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_deducao_apelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_deducao_dateHired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_deducao_dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txt_deducao_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_deducao_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txt_deducao_salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_total_deduzir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(radio_deducao_percentagem)
                        .addComponent(radio_deducao_montante)
                        .addComponent(jLabel15)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_deducao_percentagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txt_deducao_montante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(lbl_salario_deduzido))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txt_deducao_motivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(label_deducao_loggedAs)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_deducacao_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_deducacao_searchKeyReleased
        // TODO add your handling code here:
        try
        {
            String database = "SELECT * FROM staff_info WHERE ID = ?";
            pst = conn.prepareStatement(database);
            pst.setString(1,txt_deducacao_search.getText());
            rs = pst.executeQuery();
            
            
            if (rs.next()) 
                {
                    String add1 = rs.getString("ID");
                    txt_deducao_ID.setText(add1);
                    
                    String add2 = rs.getString("First_Name");
                    txt_deducao_nome.setText(add2);

                    String add3 = rs.getString("Last_Name");
                    txt_deducao_apelido.setText(add3);
                    
                    String add4 = rs.getString("Date_of_birth");
                    txt_deducao_dataNascimento.setText(add4);
                    
                    String add5 = rs.getString("Department");
                    txt_deducao_departamento.setText(add5);

                    String add6 = rs.getString("Salary");
                    txt_deducao_salario.setText(add6);
                    
                    String add7 = rs.getString("Designation");
                    txt_deducao_designacao.setText(add7);
                    
                    String add8 = rs.getString("Status");
                    txt_deducao_status.setText(add8);

                    String add9 = rs.getString("Date_Hired");
                    txt_deducao_dateHired.setText(add9);
                    
                    String add10 = rs.getString("Job_Title");
                    txt_deducao_categoria.setText(add10);
                }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Ocorreu algum erro ao carregar os dados");
        }
        finally
        {
            try
            {
                rs.close();
                pst.close();
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_txt_deducacao_searchKeyReleased

    private void txt_deducao_montanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_deducao_montanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_deducao_montanteActionPerformed

    private void radio_deducao_montanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_deducao_montanteActionPerformed
        // TODO add your handling code here:
        radio_deducao_montante.setSelected(true);
        radio_deducao_percentagem.setSelected(false);
        txt_deducao_percentagem.setEnabled(false);
        txt_deducao_montante.setEditable(true);
        txt_deducao_montante.setEnabled(true);        
        txt_deducao_percentagem.setText("");
    }//GEN-LAST:event_radio_deducao_montanteActionPerformed

    private void radio_deducao_percentagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_deducao_percentagemActionPerformed
        // TODO add your handling code here:
        radio_deducao_percentagem.setSelected(true);
        radio_deducao_montante.setSelected(false);
        txt_deducao_montante.setEnabled(false);
        txt_deducao_percentagem.setEditable(true);
        txt_deducao_percentagem.setEnabled(true);        
        txt_deducao_montante.setText("");
    }//GEN-LAST:event_radio_deducao_percentagemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Confirma o registo?", "Salvar", JOptionPane.YES_NO_OPTION);
        if(confirm == 0)
        {
            String valor3 = label_deducao_loggedAs.getText();
            
            try{
                String sql = ("INSERT INTO deducoes (Nome, Apelido, Salario, Valor_a_deduzir, Motivos, staff_id, Elaborado_por)VALUES (?,?,?,?,?,?,?)");
                pst = conn.prepareStatement(sql);
                pst.setString(1, txt_deducao_nome.getText());
                pst.setString(2, txt_deducao_apelido.getText());
                pst.setString(3, txt_deducao_salario.getText());
                pst.setString(4, lbl_total_deduzir.getText());
                pst.setString(5, txt_deducao_motivos.getText());
                pst.setString(6, txt_deducao_ID.getText());
                pst.setString(7, label_deducao_loggedAs.getText());
                
                pst.execute();
                JOptionPane.showMessageDialog(null, "Gravado com sucesso!");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            finally{
                try{
                    rs.close();
                    pst.close();
                } catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int salary = Integer.parseInt(txt_deducao_salario.getText());
        if (radio_deducao_percentagem.isSelected() == true)
        {
            int percentage = Integer.parseInt(txt_deducao_percentagem.getText());
            
            int total_percentage_deduction = salary / 100 * percentage;
            String x = String.valueOf(total_percentage_deduction);
            int salario = salary - total_percentage_deduction;
            lbl_total_deduzir.setText(x);
            lbl_salario_deduzido.setText(String.valueOf(salario));
        }
        
        if (radio_deducao_montante.isSelected() == true)
        {
            int amount = Integer.parseInt(txt_deducao_montante.getText());
            
            int total_amount_deduction = salary - amount;
            String x = String.valueOf(amount);
            lbl_total_deduzir.setText(x);
            lbl_salario_deduzido.setText(String.valueOf(total_amount_deduction));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_deducao_salarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_deducao_salarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_deducao_salarioActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                    txt_deducao_ID.setText("");
                    txt_deducao_nome.setText("");
                    txt_deducao_apelido.setText("");
                    txt_deducao_dataNascimento.setText("");
                    txt_deducao_departamento.setText("");
                    txt_deducao_salario.setText("");
                    txt_deducao_designacao.setText("");
                    txt_deducao_status.setText("");
                    txt_deducao_dateHired.setText("");
                    txt_deducao_categoria.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_deducacao_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_deducacao_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_deducacao_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deducoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deducoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deducoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deducoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deducoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel label_deducao_loggedAs;
    private javax.swing.JLabel lbl_salario_deduzido;
    private javax.swing.JLabel lbl_total_deduzir;
    private javax.swing.JRadioButton radio_deducao_montante;
    private javax.swing.JRadioButton radio_deducao_percentagem;
    private javax.swing.JTextField txt_deducacao_search;
    private javax.swing.JTextField txt_deducao_ID;
    private javax.swing.JTextField txt_deducao_apelido;
    private javax.swing.JTextField txt_deducao_categoria;
    private javax.swing.JTextField txt_deducao_dataNascimento;
    private javax.swing.JTextField txt_deducao_dateHired;
    private javax.swing.JTextField txt_deducao_departamento;
    private javax.swing.JTextField txt_deducao_designacao;
    private javax.swing.JTextField txt_deducao_montante;
    private javax.swing.JTextField txt_deducao_motivos;
    private javax.swing.JTextField txt_deducao_nome;
    private javax.swing.JTextField txt_deducao_percentagem;
    private javax.swing.JTextField txt_deducao_salario;
    private javax.swing.JTextField txt_deducao_status;
    // End of variables declaration//GEN-END:variables
}
