/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employee.payroll;
import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author lenovo
 */
public class PDF extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form PDF
     */
    public PDF() {
        initComponents();
        
        conn = db.java_db();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_PDF_search = new javax.swing.JTextField();
        txt_PDF_ID = new javax.swing.JTextField();
        txt_PDF_name = new javax.swing.JTextField();
        txt_PDF_lastName = new javax.swing.JTextField();
        txt_PDF_birthDate = new javax.swing.JTextField();
        txt_PDF_department = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_PDF_designation = new javax.swing.JTextField();
        txt_PDF_hiredDate = new javax.swing.JTextField();
        txt_PDF_jobTitle = new javax.swing.JTextField();
        txt_PDF_basicSalary = new javax.swing.JTextField();
        txt_PDF_status = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Search by ID:");

        jLabel2.setText("Employee ID:");

        jLabel3.setText("First Name:");

        jLabel4.setText("Last Name:");

        jLabel5.setText("Birth Date:");

        jLabel6.setText("Dep:");

        txt_PDF_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PDF_searchActionPerformed(evt);
            }
        });
        txt_PDF_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_PDF_searchKeyReleased(evt);
            }
        });

        jLabel7.setText("Designation:");

        jLabel8.setText("Hired Date:");

        jLabel9.setText("Job title:");

        jLabel10.setText("Basic salary:");

        jLabel11.setText("Status:");

        jButton1.setText("GERAR PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_PDF_department, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(txt_PDF_birthDate, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_PDF_lastName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_PDF_name, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_PDF_ID, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_PDF_designation)
                                    .addComponent(txt_PDF_hiredDate)
                                    .addComponent(txt_PDF_jobTitle)
                                    .addComponent(txt_PDF_basicSalary)
                                    .addComponent(txt_PDF_status, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)))
                            .addComponent(txt_PDF_search)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_PDF_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txt_PDF_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txt_PDF_designation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_PDF_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txt_PDF_hiredDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_PDF_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txt_PDF_jobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_PDF_birthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txt_PDF_basicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_PDF_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txt_PDF_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_PDF_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PDF_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PDF_searchActionPerformed

    private void txt_PDF_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PDF_searchKeyReleased
        // TODO add your handling code here:
        try
        {
            String database = "SELECT * FROM staff_info WHERE ID = ?";
            pst = conn.prepareStatement(database);
            pst.setString(1,txt_PDF_search.getText());
            rs = pst.executeQuery();
            
            
            if (rs.next()) 
                {
                    String add1 = rs.getString("ID");
                    txt_PDF_ID.setText(add1);
                    
                    String add2 = rs.getString("First_Name");
                    txt_PDF_name.setText(add2);

                    String add3 = rs.getString("Last_Name");
                    txt_PDF_lastName.setText(add3);
                    
                    String add4 = rs.getString("Date_of_birth");
                    txt_PDF_birthDate.setText(add4);
                    
                    String add5 = rs.getString("Department");
                    txt_PDF_department.setText(add5);

                    String add6 = rs.getString("Salary");
                    txt_PDF_basicSalary.setText(add6);
                    
                    String add7 = rs.getString("Designation");
                    txt_PDF_designation.setText(add7);
                    
                    String add8 = rs.getString("Status");
                    txt_PDF_status.setText(add8);

                    String add9 = rs.getString("Date_Hired");
                    txt_PDF_hiredDate.setText(add9);
                    
                    String add10 = rs.getString("Job_Title");
                    txt_PDF_jobTitle.setText(add10);
                }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Ocorreu algum erro ao carregar os dados");
        }
        finally
        {
            try
            {
                rs.close();
                pst.close();
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
        
    }//GEN-LAST:event_txt_PDF_searchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                    String add_name = txt_PDF_name.getText();
                    String add_last_name = txt_PDF_lastName.getText();
                    String add_ID = txt_PDF_ID.getText();
                    String add_birthDate = txt_PDF_birthDate.getText();                   
                    String add_departement = txt_PDF_department.getText();
                    String add_basic_salary = txt_PDF_basicSalary.getText();      
                    String add_designation = txt_PDF_designation.getText();                  
                    String add_status = txt_PDF_status.getText();
                    String add_hired_date = txt_PDF_hiredDate.getText();                  
                    String add_jobTitle = txt_PDF_jobTitle.getText();
                    
                    JFileChooser dialog = new JFileChooser();
                    
                    // O pdf vai gerar nome, apelio + Recibo salaria + pdf como nomenclatura padrao
                    dialog.setSelectedFile(new File(add_name+"_"+add_last_name+"-Recibo_salario"+".pdf"));
                    
                    int dialogResult = dialog.showSaveDialog(null);
                    if(dialogResult == JFileChooser.APPROVE_OPTION)
                    {
                        String filePath = dialog.getSelectedFile().getPath();
                    
                    
                    try{
                        String sql = "SELECT * FROM deducoes WHERE staff_id = '"+add_ID+"'";
                        pst = conn.prepareStatement(sql);
                        rs = pst.executeQuery();
                        String val_deduzido_str = rs.getString(5);
                        String deduction_reason = rs.getString(6);
                        
                        
                        
                        String database = "SELECT * FROM subsidio WHERE staff_id = '"+add_ID+"'";
                        pst = conn.prepareStatement(database);
                        rs = pst.executeQuery();
                        
                        
                        
                        int calTotal = Integer.parseInt(txt_PDF_basicSalary.getText());
                        float salary = Float.valueOf(rs.getString(9)); // 4
                        int val_deduzido = Integer.parseInt(val_deduzido_str);
                        float total = calTotal + salary - val_deduzido;
                        
                        
                        Document my_doc = new Document();
                        PdfWriter myWriter = PdfWriter.getInstance(my_doc, new FileOutputStream(filePath));
                        
                        my_doc.open();
                        
                        my_doc.add(new Paragraph("Recibo de Salario", FontFactory.getFont(FontFactory.TIMES_BOLD, 20, Font.BOLD)));
                        my_doc.add(new Paragraph(new Date().toString()));
                        my_doc.add(new Paragraph("========================================================================="));
                        my_doc.add(new Paragraph("DETALHES DO FUNCIONARIO: ", FontFactory.getFont(FontFactory.TIMES_BOLD, 20, Font.BOLD)));
                        my_doc.add(new Paragraph("Nome: "+add_name+" "+add_last_name, FontFactory.getFont(FontFactory.TIMES_ROMAN, 10, Font.PLAIN)));
                        my_doc.add(new Paragraph("Designacao: "+add_designation, FontFactory.getFont(FontFactory.TIMES_ROMAN, 10, Font.PLAIN)));
                        my_doc.add(new Paragraph("Departamento: "+add_departement, FontFactory.getFont(FontFactory.TIMES_ROMAN, 10, Font.PLAIN)));
                        my_doc.add(new Paragraph("Data de Nascimento: "+add_birthDate, FontFactory.getFont(FontFactory.TIMES_ROMAN, 10, Font.PLAIN)));
                        my_doc.add(new Paragraph("Data de contratacao: "+add_hired_date, FontFactory.getFont(FontFactory.TIMES_ROMAN, 10, Font.PLAIN)));
                        my_doc.add(new Paragraph("Titulo do trabalho: "+add_jobTitle, FontFactory.getFont(FontFactory.TIMES_ROMAN, 10, Font.PLAIN)));
                        my_doc.add(new Paragraph("========================================================================="));
                        my_doc.add(new Paragraph("SALARIO: ", FontFactory.getFont(FontFactory.TIMES_BOLD, 20, Font.BOLD)));
                        my_doc.add(new Paragraph("Salario base: "+add_basic_salary, FontFactory.getFont(FontFactory.TIMES_ROMAN, 10, Font.PLAIN)));
                        my_doc.add(new Paragraph("Status: "+add_status, FontFactory.getFont(FontFactory.TIMES_ROMAN, 10, Font.PLAIN)));
                        my_doc.add(new Paragraph("Horas Extras: "+rs.getString(2), FontFactory.getFont(FontFactory.TIMES_ROMAN, 10, Font.PLAIN)));
                        my_doc.add(new Paragraph("# Licencas: "+rs.getString(3), FontFactory.getFont(FontFactory.TIMES_ROMAN, 10, Font.PLAIN)));
                        my_doc.add(new Paragraph("Bonus: "+rs.getString(4), FontFactory.getFont(FontFactory.TIMES_ROMAN, 10, Font.PLAIN)));
                        my_doc.add(new Paragraph("Outros: "+rs.getString(5), FontFactory.getFont(FontFactory.TIMES_ROMAN, 10, Font.PLAIN)));
                        my_doc.add(new Paragraph("========================================================================="));
                        my_doc.add(new Paragraph("DESCONTOS: ", FontFactory.getFont(FontFactory.TIMES_BOLD, 20, Font.BOLD)));
                        my_doc.add(new Paragraph("Detalhes de descontos: "+deduction_reason, FontFactory.getFont(FontFactory.TIMES_ROMAN, 10, Font.PLAIN)));
                        my_doc.add(new Paragraph("Total de descontos: "+val_deduzido, FontFactory.getFont(FontFactory.TIMES_ROMAN, 10, Font.PLAIN)));
                        my_doc.add(new Paragraph("========================================================================="));
                        my_doc.add(new Paragraph("TOTAL A PAGAR: ", FontFactory.getFont(FontFactory.TIMES_BOLD, 20, Font.BOLD)));
                        my_doc.add(new Paragraph("Salario Bruto: "+salary, FontFactory.getFont(FontFactory.TIMES_ROMAN, 10, Font.PLAIN)));
                        my_doc.add(new Paragraph("Salario Liquido: "+total, FontFactory.getFont(FontFactory.TIMES_ROMAN, 10, Font.PLAIN)));
                        my_doc.add(new Paragraph("========================================================================="));
                        
                        
                        my_doc.newPage();
                        my_doc.close();
                        
                        JOptionPane.showMessageDialog(null, "Report was generated successfully!");
                        
                        
                    }catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
                    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PDF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_PDF_ID;
    private javax.swing.JTextField txt_PDF_basicSalary;
    private javax.swing.JTextField txt_PDF_birthDate;
    private javax.swing.JTextField txt_PDF_department;
    private javax.swing.JTextField txt_PDF_designation;
    private javax.swing.JTextField txt_PDF_hiredDate;
    private javax.swing.JTextField txt_PDF_jobTitle;
    private javax.swing.JTextField txt_PDF_lastName;
    private javax.swing.JTextField txt_PDF_name;
    private javax.swing.JTextField txt_PDF_search;
    private javax.swing.JTextField txt_PDF_status;
    // End of variables declaration//GEN-END:variables
}
