/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employee.payroll;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;

import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Date;
import java.text.SimpleDateFormat;
import net.proteanit.sql.DbUtils;
//import net.proteanit.sql.DbUtils;
/**
 *
 * @author lenovo
 */
public class Subsidio extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    /**
     * Creates new form Subsidio
     */
    public Subsidio() 
    {
        initComponents();
        
        conn = db.java_db();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        
        Update_table();
        label_subisido_loggedAS.setText(String.valueOf(EmployeeID.staff_id).toString());
    }
    
    private void Update_table()
    {
        try
        {
            String database = "SELECT * FROM subsidio";
            pst = conn.prepareStatement(database);
            rs = pst.executeQuery();
            table_subsidio.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        finally
        {
            try
            {
                rs.close();
                pst.close();
            }
            catch (Exception e)
            {
                        
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_subisidio_search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_subsidio_ID = new javax.swing.JTextField();
        txt_subsidio_nome = new javax.swing.JTextField();
        txt_subsidio_apelido = new javax.swing.JTextField();
        txt_subsidio_dataNascimento = new javax.swing.JTextField();
        txt_subsidio_salario = new javax.swing.JTextField();
        txt_subsidio_dep = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_subsidio = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_subsidio_horasExtras = new javax.swing.JTextField();
        txt_subsidio_licenca = new javax.swing.JTextField();
        txt_subsidio_bonus = new javax.swing.JTextField();
        txt_subsidio_outros = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_subsidio_totalExtras = new javax.swing.JTextField();
        txt_subsidio_racioHora = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        label_subsidio_A_pagar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        label_subisido_loggedAS = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Pesquisar (ID):");

        txt_subisidio_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_subisidio_searchActionPerformed(evt);
            }
        });
        txt_subisidio_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_subisidio_searchKeyReleased(evt);
            }
        });

        jLabel2.setText("Staff ID:");

        jLabel3.setText("Nome:");

        jLabel4.setText("Apelido:");

        jLabel5.setText("Data de nascimento:");

        jLabel6.setText("Salario Base:");

        jLabel7.setText("Departamento:");

        txt_subsidio_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_subsidio_IDActionPerformed(evt);
            }
        });

        txt_subsidio_apelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_subsidio_apelidoActionPerformed(evt);
            }
        });

        table_subsidio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "HorasExtras", "Licenca", "Bonus", "Outros", "Staff_ID", "Salario", "Racio", "Total", "Nome", "Apelido", "Elaborado_por"
            }
        ));
        jScrollPane1.setViewportView(table_subsidio);

        jLabel8.setText("Horas Extras:");

        jLabel9.setText("Licenca:");

        jLabel10.setText("Bonus:");

        jLabel11.setText("Outros:");

        txt_subsidio_horasExtras.setText("0");

        txt_subsidio_licenca.setText("0");
        txt_subsidio_licenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_subsidio_licencaActionPerformed(evt);
            }
        });

        txt_subsidio_bonus.setText("0");

        txt_subsidio_outros.setText("0");

        jLabel12.setText("Total Horas Extras:");

        jLabel13.setText("Racio por Hora:");

        txt_subsidio_totalExtras.setText("0");

        txt_subsidio_racioHora.setText("0");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Total a pagar:");

        label_subsidio_A_pagar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_subsidio_A_pagar.setText("0.00");

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Limpar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel16.setText("Logged In As:");

        label_subisido_loggedAS.setText("staff");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_subisidio_search, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_subsidio_salario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(txt_subsidio_dataNascimento, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_subsidio_apelido, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_subsidio_nome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_subsidio_ID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_subsidio_dep))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_subsidio_outros, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(32, 32, 32)
                                                        .addComponent(jLabel10)))
                                                .addGap(16, 16, 16))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_subsidio_bonus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txt_subsidio_licenca, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txt_subsidio_horasExtras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_subsidio_totalExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_subsidio_racioHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_subsidio_A_pagar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(2, 2, 2))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16)
                        .addGap(31, 31, 31)
                        .addComponent(label_subisido_loggedAS)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_subisidio_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_subsidio_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txt_subsidio_horasExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_subsidio_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txt_subsidio_licenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_subsidio_totalExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txt_subsidio_racioHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_subsidio_apelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txt_subsidio_bonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_subsidio_dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txt_subsidio_outros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_subsidio_salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(label_subsidio_A_pagar))
                        .addGap(5, 5, 5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_subsidio_dep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(label_subisido_loggedAS))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_subsidio_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_subsidio_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_subsidio_IDActionPerformed

    private void txt_subsidio_apelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_subsidio_apelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_subsidio_apelidoActionPerformed

    private void txt_subsidio_licencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_subsidio_licencaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_subsidio_licencaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
            {
                int value = EmployeeID.staff_id;
                
                pst = conn.prepareStatement("INSERT INTO subsidio (horas_extras, licenca_disciplinar, bonus, outros, staff_id, salario, racio, subsidio_total, first_name, last_name, elaborado_por)" + "VALUES (?,?,?,?,?,?,?,?,?,?,?)");
                pst.setString(1, txt_subsidio_horasExtras.getText());
                pst.setString(2, txt_subsidio_licenca.getText());
                pst.setString(3, txt_subsidio_bonus.getText());
                pst.setString(4, txt_subsidio_outros.getText());
                pst.setString(5, txt_subsidio_ID.getText());
                pst.setString(6, txt_subsidio_salario.getText());
                pst.setString(7, txt_subsidio_racioHora.getText());
                pst.setString(8, txt_subsidio_totalExtras.getText());
                pst.setString(9, txt_subsidio_nome.getText());
                pst.setString(10, txt_subsidio_apelido.getText());
                pst.setString(11, label_subisido_loggedAS.getText()); 
                //pst.setString(11, label_subsidio_A_pagar.getText());
                

                pst.execute();
                JOptionPane.showMessageDialog(null, "Saved");
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }
        Update_table();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_subisidio_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_subisidio_searchKeyReleased
        // TODO add your handling code here:
        try
        {
            String database = "SELECT * FROM staff_info WHERE ID = ?";
            pst = conn.prepareStatement(database);
            pst.setString(1,txt_subisidio_search.getText());
            rs = pst.executeQuery();
            
            
            if (rs.next()) 
                {
                    String add1 = rs.getString("ID");
                    txt_subsidio_ID.setText(add1);
                    
                    String add2 = rs.getString("First_Name");
                    txt_subsidio_nome.setText(add2);

                    String add3 = rs.getString("Last_Name");
                    txt_subsidio_apelido.setText(add3);
                    
                    String add4 = rs.getString("Date_of_birth");
                    txt_subsidio_dataNascimento.setText(add4);
                    
                    String add8 = rs.getString("Department");
                    txt_subsidio_dep.setText(add8);

                    String add10 = rs.getString("Salary");
                    txt_subsidio_salario.setText(add10);
                }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Ocorreu algum erro ao carregar os dados");
        }
        finally
        {
            try
            {
                rs.close();
                pst.close();
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_txt_subisidio_searchKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int salario = Integer.parseInt(txt_subsidio_salario.getText());
        int horasExtras = Integer.parseInt(txt_subsidio_horasExtras.getText());
        
        double oito = 8;
        double dias = 25;
        double dbop = 0;
        double racio_horas_extras = 1.5;
        
        //Calculate the total hours of overtime
        double total_Hextras = horasExtras * racio_horas_extras;
        String S_total_Hextras = String.valueOf(total_Hextras);
        txt_subsidio_totalExtras.setText(S_total_Hextras);
        
        //Calculate overall overtime
        dbop = salario / dias / oito;
        String S_dbop = String.valueOf(dbop);
        txt_subsidio_racioHora.setText(S_dbop);
        
        int licenca = Integer.parseInt(txt_subsidio_licenca.getText());
        int bonus = Integer.parseInt(txt_subsidio_bonus.getText());
        int outros = Integer.parseInt(txt_subsidio_outros.getText());
        
        int total = licenca + bonus + outros;
        
        double calcularTotal = total_Hextras * dbop + total;
        String S_calcularTotal = String.valueOf(calcularTotal);
        label_subsidio_A_pagar.setText(S_calcularTotal);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int confirmAdd = JOptionPane.showConfirmDialog(null, "Deseja limpar os campos!", "Limpar", JOptionPane.YES_NO_OPTION);
        
        if (confirmAdd == 0)
        {
            txt_subsidio_ID.setText("");
            txt_subsidio_nome.setText("");
            txt_subsidio_apelido.setText("");
            txt_subsidio_dataNascimento.setText("");
            txt_subsidio_salario.setText("");
            txt_subsidio_dep.setText("");
            txt_subsidio_totalExtras.setText("0");
            txt_subsidio_racioHora.setText("0");
            label_subsidio_A_pagar.setText("0.00");
            txt_subsidio_horasExtras.setText("0");
            txt_subsidio_licenca.setText("0");
            txt_subsidio_bonus.setText("0");
            txt_subsidio_outros.setText("0");
            txt_subisidio_search.setText("");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_subisidio_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_subisidio_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_subisidio_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Subsidio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Subsidio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Subsidio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Subsidio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Subsidio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_subisido_loggedAS;
    private javax.swing.JLabel label_subsidio_A_pagar;
    private javax.swing.JTable table_subsidio;
    private javax.swing.JTextField txt_subisidio_search;
    private javax.swing.JTextField txt_subsidio_ID;
    private javax.swing.JTextField txt_subsidio_apelido;
    private javax.swing.JTextField txt_subsidio_bonus;
    private javax.swing.JTextField txt_subsidio_dataNascimento;
    private javax.swing.JTextField txt_subsidio_dep;
    private javax.swing.JTextField txt_subsidio_horasExtras;
    private javax.swing.JTextField txt_subsidio_licenca;
    private javax.swing.JTextField txt_subsidio_nome;
    private javax.swing.JTextField txt_subsidio_outros;
    private javax.swing.JTextField txt_subsidio_racioHora;
    private javax.swing.JTextField txt_subsidio_salario;
    private javax.swing.JTextField txt_subsidio_totalExtras;
    // End of variables declaration//GEN-END:variables
}
